apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-web
  template:
    metadata:
      labels:
        app: cluster-web
    spec:
      containers:
      - name: cluster-web
        image: diedona/rotten-potatoes:v1
        ports:
          - containerPort: 5000
        env:
          - name: MONGODB_DB
            value: admin
          - name: MONGODB_HOST
            value: cluster-mongo-service
          - name: MONGODB_PORTS
            value: "27017"
          - name: MONGODB_USERNAME
            value: mongouser
          - name: MONGODB_PASSWORD
            value: mongopwd